language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 5.5
  - 5.6
  - 7.0

install:
  - composer install --prefer-source

before_script:
  - composer selfupdate
  - composer update --prefer-dist

script:
  - phpunit
