language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 5.5
  - 5.6
  - 7.0

install:
  - composer selfupdate
  - composer install --prefer-source

before_script:
  - if [[ $TRAVIS_PHP_VERSION = '7.0' ]]; then vendor/fabpot/php-cs-fixer/php-cs-fixer fix . --diff --dry-run -v --level=symfony; fi

script:
  - phpunit
