<?php

/**
 * Test class
 */
class Test
{
    /**
     * Method
     */
    public function method001()
    {
    }

    /**
     * Method
     */
    public function method002()
    {
    }

    /**
     * Method
     */
    public function method003()
    {
    }

    /**
     * Method
     */
    public function method004()
    {
    }

    /**
     * Method
     */
    public function method005()
    {
    }

    /**
     * Method
     */
    public function method006()
    {
    }

    /**
     * Method
     */
    public function method007()
    {
    }

    /**
     * Method
     */
    public function method008()
    {
    }

    /**
     * Method
     */
    public function method009()
    {
    }

    /**
     * Method
     */
    public function method010()
    {
    }

    /**
     * Method
     */
    public function method011()
    {
    }
}

