<?php

class Test
{
    const RED = '1';

    const BL = '2';

    const LONGEST_CONSTANT_NAME_EVER_LONGEST_CONSTANT_NAME_EVER = '2';
}

class TooMuchLongClassNameTooMuchLongClassNameTooMuchLongClassName
{
}

class ValidClassName
{
    public function te()
    {
    }
}

function test()
{
}

function te()
{
}

function veryLongFunctionNameVeryLongFunctionName()
{
}

class Te
{
}


class Test
{
    public $testing = 1;

    public $te = 0;

    public $veryLongPropertyNameVeryLongPropertyName = 2;

    public $id = 3;

    public function __construct($t)
    {
        $this->te = $t;
    }

    public function testing()
    {
        $red = 0;
        $green = 1;
        $bl = 2;

        for ($i = 0; $i < range(0, 9); $i++) {
            echo $i;
        }

        $veryLongPropertyNameVeryLongPropertyName = 3;
    }
}
