<?php

class Test
{
    const BL = '2';

    const LONGEST_CONSTANT_NAME_EVER_LONGEST_CONSTANT_NAME_EVER = '2';
}

class ValidClassName
{
    public function te()
    {
    }
}

function te()
{
}

function veryLongFunctionName()
{
}

class Te
{
}

trait Tr
{
}

class Test
{
    public $te = 0;

    public $veryLongPropertyNameVeryLongPropertyName = 2;

    public $id = 3;

    public function __construct($t)
    {
        $this->te = $t;
    }

    public function testing()
    {
        $bl = 2;

        for ($i = 0; $i < range(0, 9); $i++) {
            echo $i;
        }
        $veryLongPropertyNameVeryLongPropertyName = 3;
    }
}
