<?php

class TestClass
{
    /**
     * @var array
     */
    protected $array1;

    /**
     * @var array
     */
    protected $array2;
}

class OkTestClass
{
    /**
     * @var array
     */
    protected $array1;
}

trait TestTrait
{
    /**
     * @var array
     */
    protected $array1;

    /**
     * @var array
     */
    protected $array2;
}

trait OkTestTrait
{
    /**
     * @var array
     */
    protected $array1;
}
