<?php

class TestClass
{
    /**
     * @var Color
     */
    protected $color1;

    /**
     * @var Color
     */
    protected $color2;

    /**
     * @var Color
     */
    protected $color3;

    /**
     * @var Color
     */
    protected $color4;

    /**
     * @var Color
     */
    protected $color5;

    /**
     * @var Color
     */
    protected $color6;
}

class OkTestClass
{
    /**
     * @var array
     */
    protected $array1;

    /**
     * @var bool
     */
    protected $boolean1;

    /**
     * @var boolean
     */
    protected $boolean2;

    /**
     * @var callable
     */
    protected $callable1;

    /**
     * @var decimal
     */
    protected $decimal1;

    /**
     * @var double
     */
    protected $double1;

    /**
     * @var float
     */
    protected $float1;

    /**
     * @var int
     */
    protected $integer1;

    /**
     * @var integer
     */
    protected $integer2;

    /**
     * @var resource
     */
    protected $resource1;

    /**
     * @var string
     */
    protected $string1;

    /**
     * @var Color
     */
    protected $color1;

    /**
     * @var Color
     */
    protected $color2;

    /**
     * @var Color
     */
    protected $color3;
}

trait TestTrait
{
    /**
     * @var array
     */
    protected $array1;

    /**
     * @var array
     */
    protected $array2;

    /**
     * @var Color
     */
    protected $color1;

    /**
     * @var Color
     */
    protected $color2;

    /**
     * @var Color
     */
    protected $color3;

    /**
     * @var Color
     */
    protected $color4;

    /**
     * @var Color
     */
    protected $color5;

    /**
     * @var Color
     */
    protected $color6;
}

trait OkTestTrait
{
    /**
     * @var array
     */
    protected $array1;
}
